version: '3.4'

services:
  xoros-builder:
    build:
      context: .
      network: host
    image: ghcr.io/xoros-repo/xoros-builder:latest
    restart: unless-stopped
    entrypoint: github-runner.sh
    cpu_count: 8
    mem_reservation: 16g
    environment:
      - GITHUB_RUNNER_REPO
      - GITHUB_RUNNER_TOKEN
      - BUILDER_CACHE_DIR=/home/builder/cache
    volumes:
      - builder_cache:/home/builder/cache

volumes:
  builder_cache:
