version: '3'

services:
  xoros-builder:
    build: .
    restart: unless-stopped
    cpu_count: 8
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: '32G'
    environment:
      - GITHUB_REPO
      - GITHUB_RUNNER_TOKEN
    volumes:
      - type: volume
        source: xoros_builder
        target: /home/builder
        volume:
          nocopy: true

volumes:
  xoros_builder:
