version: '3'

services:
  xoros-builder:
    build: .
    restart: unless-stopped
    entrypoint: github-runner.sh
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: '32G'
    environment:
      - GITHUB_RUNNER_REPO
      - GITHUB_RUNNER_TOKEN
      - YOCTO_CACHE_DIR
    volumes:
      - type: volume
        source: xoros_builder_cache
        target: ${YOCTO_CACHE_DIR}
        volume:
          nocopy: true

volumes:
  xoros_builder_cache:
