version: '3'

services:
  xoros-builder:
    build: .
    restart: unless-stopped
    entrypoint: github-runner.sh
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: '32G'
    environment:
      - GITHUB_RUNNER_REPO
      - GITHUB_RUNNER_TOKEN
      - BUILDER_CACHE_DIR=/home/builder/cache
    volumes:
      - builder_cache:/home/builder/cache

volumes:
  builder_cache:
